id: I74A4FD8A
legacy_id: P010770
ocr_import_info:
  bdrc_scan_id: W8LS17463
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T20:30:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:50:23.861510+00:00'
last_modified: 2022-09-04 11:53:00.802115
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17463
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17463
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇིགས་མེད་འཕྲིན་ལས་རྒྱ་མཚོ།
  author: བླ་ཁོ་འཇིགས་མེད་འཕྲིན་ལས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6387527856979419
  ocr_word_median_confidence_index: 0.6800000071525574
quality: null
bases:
  I8LS17479:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17479
      total_pages: 869
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I8LS17479.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6864230038816787
    legacy_id: v006
  I8LS17474:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17474
      total_pages: 860
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17474.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5612053045522177
    legacy_id: v001
  I8LS17476:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17476
      total_pages: 866
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I8LS17476.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6474481905726018
    legacy_id: v003
  I8LS17475:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17475
      total_pages: 836
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I8LS17475.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6214114786419507
    legacy_id: v002
  I8LS17478:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17478
      total_pages: 818
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I8LS17478.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6663052455015483
    legacy_id: v005
  I8LS17477:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17477
      total_pages: 828
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I8LS17477.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6514564987560902
    legacy_id: v004
  I8LS17480:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17480
      total_pages: 416
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I8LS17480.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.5890913584281628
    legacy_id: v007
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
