id: I74A4FD8A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:35:12+00:00'
last_modified: '2022-06-08T17:24:07.635494+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17463
  title: གསུང་འབུམ། འཇིགས་མེད་འཕྲིན་ལས་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4C88:
      image_group_id: I8LS17474
      title: ''
      total_pages: 860
      order: 1
      base_file: 4C88.txt
    '6664':
      image_group_id: I8LS17475
      title: ''
      total_pages: 836
      order: 2
      base_file: 6664.txt
    9C75:
      image_group_id: I8LS17476
      title: ''
      total_pages: 866
      order: 3
      base_file: 9C75.txt
    8C8C:
      image_group_id: I8LS17477
      title: ''
      total_pages: 828
      order: 4
      base_file: 8C8C.txt
    '3155':
      image_group_id: I8LS17478
      title: ''
      total_pages: 818
      order: 5
      base_file: 3155.txt
    B50B:
      image_group_id: I8LS17479
      title: ''
      total_pages: 869
      order: 6
      base_file: B50B.txt
    D4DD:
      image_group_id: I8LS17480
      title: ''
      total_pages: 416
      order: 7
      base_file: D4DD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
